Repository Learnathon-By-Geeky-Solutions/devs, pull requests merged in 2025-04, with the labels that each got.

#38 feat: implement pagination & better exception handling
  src/main/java/com/devs/roamance/config/SecurityConfig.java
  src/main/java/com/devs/roamance/constant/ResponseMessage.java
  src/main/java/com/devs/roamance/controller/UserController.java
  src/main/java/com/devs/roamance/dto/ValidationErrorDto.java
  src/main/java/com/devs/roamance/dto/response/ValidationErrorResponseDto.java
  src/main/java/com/devs/roamance/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/devs/roamance/repository/UserRepository.java
  src/main/java/com/devs/roamance/service/BaseService.java
  src/main/java/com/devs/roamance/service/UserService.java
  src/main/java/com/devs/roamance/service/impl/UserServiceImpl.java
  src/main/java/com/devs/roamance/util/PaginationSortingUtil.java
Labels: enhancement, backend

#42 refactor: refactor code & folder structure
  src/main/java/com/devs/roamance/config/SecurityConfig.java
  src/main/java/com/devs/roamance/constant/ResponseMessage.java
  src/main/java/com/devs/roamance/controller/UserController.java
  src/main/java/com/devs/roamance/dto/response/UserDto.java
  src/main/java/com/devs/roamance/dto/response/UserListResponseDto.java
  src/main/java/com/devs/roamance/dto/response/UserResponseDto.java
  src/main/java/com/devs/roamance/dto/response/ValidationErrorDto.java
  src/main/java/com/devs/roamance/dto/response/ValidationErrorResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/JournalDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/JournalListResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SubsectionDetailDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SubsectionDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SubsectionListResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SubsectionResponseDto.java
  src/main/java/com/devs/roamance/exception/AuthenticatedUserNotFoundException.java
  src/main/java/com/devs/roamance/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/devs/roamance/model/Role.java
  src/main/java/com/devs/roamance/model/User.java
  src/main/java/com/devs/roamance/security/JwtUtils.java
  src/main/java/com/devs/roamance/service/UserService.java
  src/main/java/com/devs/roamance/service/impl/JournalServiceImpl.java
  src/main/java/com/devs/roamance/service/impl/SubsectionServiceImpl.java
  src/main/java/com/devs/roamance/service/impl/UserServiceImpl.java
  src/main/java/com/devs/roamance/util/UserUtil.java
Labels: enhancement, chore, backend, refactor

#59 feat: add user preferences management
  roamance/src/app/api/cloudinary/upload/route.ts
  roamance/src/components/profile/index.tsx
  roamance/src/components/profile/preferences/accommodation-section.tsx
  roamance/src/components/profile/preferences/activities-section.tsx
  roamance/src/components/profile/preferences/budget-section.tsx
  roamance/src/components/profile/preferences/climate-section.tsx
  roamance/src/components/profile/preferences/cuisine-section.tsx
  roamance/src/components/profile/preferences/index.tsx
  roamance/src/components/profile/preferences/preference-header.tsx
  roamance/src/components/profile/preferences/save-button.tsx
  roamance/src/components/profile/preferences/travel-style-section.tsx
  roamance/src/components/profile/profile-header.tsx
  roamance/src/components/profile/profile-preferences.tsx
  roamance/src/components/profile/profile-tabs.tsx
  roamance/src/constants/api.ts
  roamance/src/service/auth-service.ts
  roamance/src/service/cloudinary-service.ts
  roamance/src/service/user-service.ts
  roamance/src/types/index.ts
  roamance/src/types/response.ts
  roamance/src/types/user.ts
  src/main/java/com/devs/roamance/constant/ResponseMessage.java
  src/main/java/com/devs/roamance/controller/UserPreferencesController.java
  src/main/java/com/devs/roamance/dto/request/user/UserPreferencesRequestDto.java
  src/main/java/com/devs/roamance/dto/response/user/UserPreferencesDto.java
  src/main/java/com/devs/roamance/dto/response/user/UserPreferencesListResponseDto.java
  src/main/java/com/devs/roamance/dto/response/user/UserPreferencesResponseDto.java
  src/main/java/com/devs/roamance/model/user/User.java
  src/main/java/com/devs/roamance/model/user/preference/AccommodationType.java
  src/main/java/com/devs/roamance/model/user/preference/ActivityType.java
  src/main/java/com/devs/roamance/model/user/preference/BudgetLevel.java
  src/main/java/com/devs/roamance/model/user/preference/ClimatePreference.java
  src/main/java/com/devs/roamance/model/user/preference/CuisineType.java
  src/main/java/com/devs/roamance/model/user/preference/TravelStyle.java
  src/main/java/com/devs/roamance/model/user/preference/UserPreferences.java
  src/main/java/com/devs/roamance/repository/UserPreferencesRepository.java
  src/main/java/com/devs/roamance/service/UserPreferencesService.java
  src/main/java/com/devs/roamance/service/impl/UserPreferencesServiceImpl.java
Labels: frontend, backend, feature

#64 feat: add GitHub Actions workflow for deploying Next.js site to GitHub Pages
  .github/workflows/nextjs.yml
  roamance/src/components/profile/profile-saved-places.tsx
  roamance/src/components/profile/profile-trips.tsx
Labels: feature

#73 fix: nextjs static page generation and next.config.ts config
  .github/workflows/nextjs.yml
  roamance/next.config.ts
  roamance/package.json
  roamance/yarn.lock
Labels: enhancement

#75 fix: nextjs static page generation and next.config.ts config
  .github/workflows/nextjs.yml
  roamance/next.config.ts
  roamance/package.json
  roamance/yarn.lock
Labels: enhancement

#79 fix: image handling and dynamic basePath configuration
  roamance/next.config.ts
  roamance/src/components/auth/AuthHero.tsx
  roamance/src/components/common/image-wrapper.tsx
  roamance/src/components/footer.tsx
  roamance/src/components/home/globe/place-images-carousel.tsx
  roamance/src/components/index.ts
  roamance/src/components/navigation/NavLogo.tsx
  roamance/src/components/profile/index.tsx
  roamance/src/components/profile/profile-header.tsx
  roamance/src/components/profile/profile-saved-places.tsx
  roamance/src/components/profile/profile-trips.tsx
Labels: bug, enhancement

#81 fix: assets prefix issue for gh pages
  roamance/next.config.ts
  roamance/src/components/auth/AuthHero.tsx
  roamance/src/components/common/image-wrapper.tsx
  roamance/src/components/footer.tsx
  roamance/src/components/home/globe/place-images-carousel.tsx
  roamance/src/components/index.ts
  roamance/src/components/navigation/NavLogo.tsx
  roamance/src/components/profile/index.tsx
  roamance/src/components/profile/profile-header.tsx
  roamance/src/components/profile/profile-saved-places.tsx
  roamance/src/components/profile/profile-trips.tsx
Labels: bug, enhancement

#82 feat: add multimodal rag for context aware search
  .env.example
  build.gradle
  src/main/java/com/devs/roamance/constant/AiSystemInstruction.java
  src/main/java/com/devs/roamance/constant/ResponseMessage.java
  src/main/java/com/devs/roamance/controller/AiController.java
  src/main/java/com/devs/roamance/controller/GeminiAiController.java
  src/main/java/com/devs/roamance/dto/request/ai/MultiModalRagRequestDto.java
  src/main/java/com/devs/roamance/dto/response/ai/EmbeddingResponse.java
  src/main/java/com/devs/roamance/dto/response/ai/PostIdListRagSearchDto.java
  src/main/java/com/devs/roamance/dto/response/ai/TidbitsAndSafetyDto.java
  src/main/java/com/devs/roamance/service/AiService.java
  src/main/java/com/devs/roamance/service/GeminiAiService.java
  src/main/java/com/devs/roamance/service/impl/AiServiceImpl.java
  src/main/java/com/devs/roamance/service/impl/GeminiAiServiceImpl.java
  src/main/java/com/devs/roamance/service/impl/PostServiceImpl.java
  src/main/java/com/devs/roamance/util/GeminiModelUtil.java
  src/main/java/com/devs/roamance/util/NomicImageEmbeddingUtil.java
  src/main/java/com/devs/roamance/util/PostUtil.java
  src/main/java/com/devs/roamance/util/RagUtil.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: enhancement, backend, feature

#91 feat: add social features with posts, comments and other functionality
  roamance/next.config.ts
  roamance/package.json
  roamance/src/api/roamance-api.ts
  roamance/src/app/layout.tsx
  roamance/src/app/social/destinations/page.tsx
  roamance/src/app/social/discover/page.tsx
  roamance/src/app/social/explore/page.tsx
  roamance/src/app/social/hashtags/page.tsx
  roamance/src/app/social/layout.tsx
  roamance/src/app/social/messages/page.tsx
  roamance/src/app/social/page.tsx
  roamance/src/app/social/saved/page.tsx
  roamance/src/components/common/button/dialog-x-button.tsx
  roamance/src/components/maps/MapController.tsx
  roamance/src/components/maps/RouteVisualization.tsx
  roamance/src/components/maps/directions/TurnByTurnList.tsx
  roamance/src/components/maps/markers/DestinationMarker.tsx
  roamance/src/components/navigation/Navbar.tsx
  roamance/src/components/profile/journal/journal-card.tsx
  roamance/src/components/profile/journal/journal-detail-view.tsx
  roamance/src/components/social/SideNavigation.tsx
  roamance/src/components/social/comment/comment-card.tsx
  roamance/src/components/social/comment/comment-dialog.tsx
  roamance/src/components/social/comment/comment-form.tsx
  roamance/src/components/social/comment/comment-section.tsx
  roamance/src/components/social/comment/index.ts
  roamance/src/components/social/feed/empty-feed.tsx
  roamance/src/components/social/feed/feed-skeleton.tsx
  roamance/src/components/social/feed/social-feed.tsx
  roamance/src/components/social/post/post-actions.tsx
  roamance/src/components/social/post/post-card.tsx
  roamance/src/components/social/post/post-content.tsx
  roamance/src/components/social/post/post-creator.tsx
  roamance/src/components/social/post/post-header.tsx
  roamance/src/components/social/post/post-media.tsx
  roamance/src/components/social/post/post-menu.tsx
  roamance/src/components/social/saved-posts/saved-posts-section.tsx
  roamance/src/components/social/trending-section.tsx
  roamance/src/components/social/trending/trending-item.tsx
  roamance/src/components/social/trending/trending-section.tsx
  roamance/src/components/social/trending/trending-user.tsx
  roamance/src/components/social/ui/shared-components.tsx
  roamance/src/components/ui/dialog.tsx
  roamance/src/components/ui/scroll-area.tsx
  roamance/src/constants/api.ts
  roamance/src/constants/routes.ts
  roamance/src/context/SocialContext.tsx
  roamance/src/service/social-service.ts
  roamance/src/types/index.ts
  roamance/src/types/response.ts
  roamance/src/types/social.ts
  roamance/src/utils/format.ts
  roamance/tailwind.config.js
  roamance/yarn.lock
Labels: frontend, refactor, feature

#113 Feature/develop task 88 add itinerary management UI
  roamance/package.json
  roamance/src/app/itinerary/activity/create/page.tsx
  roamance/src/app/itinerary/activity/edit/page.tsx
  roamance/src/app/itinerary/create/page.tsx
  roamance/src/app/itinerary/day-plan/create/page.tsx
  roamance/src/app/itinerary/day-plan/edit/page.tsx
  roamance/src/app/itinerary/details/page.tsx
  roamance/src/app/itinerary/layout.tsx
  roamance/src/app/itinerary/page.tsx
  roamance/src/components/common/pie-chart.tsx
  roamance/src/components/itinerary/ActivityForm.tsx
  roamance/src/components/itinerary/ActivityList.tsx
  roamance/src/components/itinerary/CostTracker.tsx
  roamance/src/components/itinerary/DayPlanCard.tsx
  roamance/src/components/itinerary/DayPlanForm.tsx
  roamance/src/components/itinerary/ItineraryCard.tsx
  roamance/src/components/itinerary/ItineraryDashboard.tsx
  roamance/src/components/itinerary/ItineraryDetail.tsx
  roamance/src/components/ui/button.tsx
  roamance/src/constants/api.ts
  roamance/src/service/activity-service.ts
  roamance/src/service/dayplan-service.ts
  roamance/src/service/itinerary-service.ts
  roamance/src/types/activity.ts
  roamance/src/types/index.ts
  roamance/src/types/itinerary.ts
  roamance/yarn.lock
Labels: frontend, feature

#114 fix: fix build.gradle & remove controller test
  build.gradle
  src/test/java/com/devs/roamance/controller/ActivityControllerTest.java
  src/test/java/com/devs/roamance/controller/AdminControllerTest.java
  src/test/java/com/devs/roamance/controller/AiControllerTest.java
  src/test/java/com/devs/roamance/controller/AuthControllerTest.java
  src/test/java/com/devs/roamance/controller/ChatControllerTest.java
  src/test/java/com/devs/roamance/controller/CommentControllerTest.java
  src/test/java/com/devs/roamance/controller/DayPlanControllerTest.java
  src/test/java/com/devs/roamance/controller/ItineraryControllerTest.java
  src/test/java/com/devs/roamance/controller/JournalControllerTest.java
  src/test/java/com/devs/roamance/controller/MessageControllerTest.java
  src/test/java/com/devs/roamance/controller/PostControllerTest.java
  src/test/java/com/devs/roamance/controller/RealTimeChatControllerTest.java
  src/test/java/com/devs/roamance/controller/SubsectionControllerTest.java
  src/test/java/com/devs/roamance/controller/UserControllerTest.java
  src/test/java/com/devs/roamance/controller/UserInfoControllerTest.java
  src/test/java/com/devs/roamance/controller/UserPreferencesControllerTest.java
Labels: chore

#115 fix: remove WebMvcTestConfig
  build.gradle
  src/test/java/com/devs/roamance/config/WebMvcTestConfig.java
Labels: chore
