Repository Learnathon-By-Geeky-Solutions/devs, pull requests merged in 2025-03, with the labels that each got.

#25 feat: add travel journal entities and dtos
  .copilotignore
  src/main/java/com/devs/roamance/dto/request/LocationCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/LocationUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/ActivitySubsectionCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/ActivitySubsectionUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/JournalCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/JournalUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/RouteSubsectionCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/RouteSubsectionUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/SightseeingSubsectionCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/SightseeingSubsectionUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/SubsectionCreateRequestDto.java
  src/main/java/com/devs/roamance/dto/request/travel/journal/SubsectionUpdateRequestDto.java
  src/main/java/com/devs/roamance/dto/response/LocationResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/ActivitySubsectionResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/JournalBriefResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/JournalDetailResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/RouteSubsectionResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SightseeingSubsectionResponseDto.java
  src/main/java/com/devs/roamance/dto/response/travel/journal/SubsectionResponseDto.java
  src/main/java/com/devs/roamance/model/Location.java
  src/main/java/com/devs/roamance/model/travel/journal/ActivitySubsection.java
  src/main/java/com/devs/roamance/model/travel/journal/Journal.java
  src/main/java/com/devs/roamance/model/travel/journal/RouteSubsection.java
  src/main/java/com/devs/roamance/model/travel/journal/SightseeingSubsection.java
  src/main/java/com/devs/roamance/model/travel/journal/Subsection.java
  src/main/java/com/devs/roamance/model/travel/journal/SubsectionType.java
Labels: enhancement

#28 feat: create landing page
  .github/workflows/nextjs.yml
  roamance/.copilotignore
  roamance/package.json
  roamance/src/app/globals.css
  roamance/src/app/layout.tsx
  roamance/src/app/page.tsx
  roamance/src/components/Icons.tsx
  roamance/src/components/common/theme-provider.tsx
  roamance/src/components/common/theme-toggle.tsx
  roamance/src/components/footer.tsx
  roamance/src/components/home/destination-card.tsx
  roamance/src/components/home/destination-showcase.tsx
  roamance/src/components/home/feature-showcase.tsx
  roamance/src/components/home/hero-section.tsx
  roamance/src/components/home/quick-link-card.tsx
  roamance/src/components/navbar.tsx
  roamance/src/components/theme-toggle.tsx
  roamance/src/components/ui/button.tsx
  roamance/src/components/ui/sonner.tsx
  roamance/src/constants/routes.ts
  roamance/tailwind.config.js
  roamance/yarn.lock
Labels: enhancement, initialization

#35 feat: implement pagination & better error handling
  src/main/java/com/devs/roamance/config/SecurityConfig.java
  src/main/java/com/devs/roamance/constant/ResponseMessage.java
  src/main/java/com/devs/roamance/controller/UserController.java
  src/main/java/com/devs/roamance/dto/ValidationErrorDto.java
  src/main/java/com/devs/roamance/dto/response/ValidationErrorResponseDto.java
  src/main/java/com/devs/roamance/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/devs/roamance/repository/UserRepository.java
  src/main/java/com/devs/roamance/service/BaseService.java
  src/main/java/com/devs/roamance/service/UserService.java
  src/main/java/com/devs/roamance/service/impl/UserServiceImpl.java
  src/main/java/com/devs/roamance/util/PaginationSortingUtil.java
Labels: enhancement, backend
